Step4
zunior-team/java-ladder pull request #4
Opened 2020-05-29 10:35 UTC by nokchax

2020-05-29 14:47 UTC, gale34 commented on src/main/java/ladder/domain/ladder/strategy/LadderInitStrategies.java
> +public enum LadderInitStrategies implements LadderInitStrategy {
enum은 enum대로 두고, LadderInitStrategies를 인스턴스 변수로 두는 클래스가 LadderInitStrategy를 구현하는 건 어떨까요? 그러니까 일종의 구성(composition) 구조를 사용하는 건데요. 그러면 뭔가 코드 반복도 줄이고 구조도 깔끔하게 될 것 같은 느낌이 듭니다.

2020-05-29 14:48 UTC, gale34 commented on src/main/java/ladder/domain/ladder/strategy/LadderInitStrategy.java
> +    LadderHeightStrategy getLadderHeightStrategy();
어떤 공통된 행위를 추상화했다기보단, 상태 조회 기능만 정의한 인터페이스라(getter만 있는) 어색한 느낌이 드네요. 캡슐화의 관점에서도, 내부 구조가 드러나는 듯한 기분이 듭니다. 
차라리 `boolean isGenerable()`과 `int decideHeight()`를 추상화하는게 낫지 않을까 싶은데..(구현체가 FootStepCreateStrategy , LadderHeightStrategy 사용하던 말던 상관없이..)
선임님 생각은 어떠신가요???

2020-05-29 14:56 UTC, gale34 requested changes
독특한 전략 패턴을 사용하셨군요. 음...부가적인 거라 딱히 코멘트 달건 없지만, 이 구조에서는 구성 구조가 더 좋지 않을 까 싶어서 몇 개 코멘트 남깁니다. 한번 생각해보시고 반영과 의견 공유해주세요!

2020-05-30 02:02 UTC, nokchax commented on src/main/java/ladder/domain/ladder/strategy/LadderInitStrategies.java
> +public enum LadderInitStrategies implements LadderInitStrategy {
아 이렇게 둔 이유는 enum만 사용할 경우 테스트 클래스에서 원하는 생성전략을 생성 못하기 때문에 인터페이스를 둔 구조라서.. 흠 좋은 방법이 없을까요?

2020-05-30 02:03 UTC, nokchax commented on src/main/java/ladder/domain/ladder/strategy/LadderInitStrategy.java
> +    LadderHeightStrategy getLadderHeightStrategy();
ㅋㅋㅋㅋ 위에 달았듯이 만들게 된 이유때문에 추상화로 안보이네요 음... 다른 방법을 찾아봐야겠슴다

2020-05-30 17:27 UTC, nokchax commented on src/main/java/ladder/domain/ladder/strategy/LadderInitStrategies.java
> +public enum LadderInitStrategies implements LadderInitStrategy {
어떤식으로 하는건지 이해를 못했어요 ㅠ, 코드로 설명좀

2020-05-31 06:39 UTC, gale34 commented on src/main/java/ladder/domain/ladder/strategy/LadderInitStrategies.java
> +public enum LadderInitStrategies implements LadderInitStrategy {
```
public enum LadderLevel {
    HARD_LEVEL("상", 7, 4, 2),
    MEDIUM_LEVEL("중", 5, 2, 5),
    EASY("하", 2, 3, 7);

    private static final Map<String, LadderLevel> LEVELS =
            Arrays.stream(values())
                    .collect(Collectors.toMap(LadderLevel::getLevel, Function.identity()));

    private final String level;
    private final int base;
    private final int range;
    private final int standard;

    LadderLevel(final String level, final int base, final int range, final int standard) {
        this.level = level;
        this.base = base;
        this.range = range;
        this.standard = standard;
    }


    public static LadderLevel of(final String type) {
        if (!LEVELS.containsKey(type)) {
            throw new IllegalArgumentException("Unknown type : " + type);
        }

        return LEVELS.get(type);
    }

    private String getLevel() {
        return level;
    }

    public int getBase() {
        return base;
    }

    public int getRange() {
        return range;
    }

    public int getStandard() {
        return standard;
    }
}

...
public interface LadderInitStrategy {
    boolean isGenerable();

    int decideHeight();
}

...
public class LadderInitStrategyWithLevel implements LadderInitStrategy {

    private FootStepCreateStrategy footStepCreateStrategy;
    private LadderHeightStrategy ladderHeightStrategy;

    public LadderInitStrategyWithLevel(LadderLevel ladderLevel) {
        this.footStepCreateStrategy = new RandomChanceStrategy(ladderLevel.getStandard());
        this.ladderHeightStrategy = new RandomHeightStrategy(ladderLevel.getBase(), ladderLevel.getRange());
    }

    @Override
    public boolean isGenerable() {
        return footStepCreateStrategy.isGenerable();
    }

    @Override
    public int decideHeight() {
        return ladderHeightStrategy.decideHeight();
    }
}
```
음...제가 생각한 구조는 대강 이런데요 (객체지향 생활 체조원칙은 잠시 잊어두고 대강 구조만 짜보았습니다 하하)
LadderInitStrategy의 다른 구현체에서 FootStepCreateStrategy , LadderHeightStrategy 을 받게 하면 기타 테스트 전략 객체도 만들 수 있을 것 같은데...선임님 생각은 어떠신가요???

2020-06-01 06:05 UTC, merged